# Generated by Django 5.2.8 on 2025-12-02 11:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('custom', 'Custom')], default='male', max_length=20),
        ),
    ]
