# Generated by Django 5.2.8 on 2025-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quiz_public_id_quiz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_public',
        ),
    ]
