# Generated by Django 5.2.8 on 2025-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_is_public_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
