# Generated by Django 5.2.8 on 2025-12-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_add_is_featured_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quizzes.quiz'),
        ),
    ]
